server:
  port: 8081
camunda:
  endpoint: localhost:8080/rest
  worker-topic: Worker-Polling-1
  worker-id: Worker-Polling-1
  worker-schedule: 5000
  worker-max-taks: 10
  worker-starter-thread: 5
  worker-starter-max-queue-size: 3
  worker-service-thread: 10
  worker-service-max-queue-size: 1
  worker-time: time1
